import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "@/providers/NextThemeProvider";

const inter = Inter({
  
  subsets: ["latin"],
});



export const metadata = {
  title: "StudyNook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.className}  h-full antialiased`}  
    >
      <body className="min-h-full flex flex-col bg-white text-black dark:bg-black dark:text-white">
        <NextThemeProvider>
          <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <Toaster /></NextThemeProvider>
      </body>
    </html>
  );
}
